### ISSUE TITLE
[Bug]: Customize Stripe Integration guide failing (paymentElement)

### ISSUE THREAD

**Issue by 420coupe** [medusajs/nextjs-starter-medusa#451]
### Package.json file

```JSON
{
  "name": "medusa-next",
  "version": "1.0.3",
  "private": true,
  "description": "Next.js Starter to be used with Medusa V2",
  "keywords": [
    "medusa-storefront"
  ],
  "scripts": {
    "dev": "next dev --turbopack -p 8000",
    "build": "next build",
    "start": "next start -p 8000",
    "lint": "next lint",
    "analyze": "ANALYZE=true next build"
  },
  "dependencies": {
    "@headlessui/react": "^2.2.0",
    "@medusajs/icons": "latest",
    "@medusajs/js-sdk": "latest",
    "@medusajs/ui": "latest",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@radix-ui/react-accordion": "^1.2.1",
    "@stripe/react-stripe-js": "^1.7.2",
    "@stripe/stripe-js": "^1.29.0",
    "@supabase/supabase-js": "^2.45.4",
    "algoliasearch": "^4.20.0",
    "lodash": "^4.17.21",
    "next": "^15.0.3",
    "pg": "^8.11.3",
    "qs": "^6.12.1",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-country-flag": "^3.1.0",
    "react-dom": "19.0.0-rc-66855b96-20241106",
    "react-instantsearch-hooks-web": "^6.47.3",
    "react-intersection-observer": "^9.3.4",
    "react-swipeable": "^7.0.1",
    "server-only": "^0.0.1",
    "sharp": "^0.33.5",
    "tailwindcss-radix": "^2.8.0",
    "webpack": "^5"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@medusajs/types": "latest",
    "@medusajs/ui-preset": "latest",
    "@types/lodash": "^4.14.195",
    "@types/node": "17.0.21",
    "@types/pg": "^8.11.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@types/react-instantsearch-dom": "^6.12.3",
    "ansi-colors": "^4.1.3",
    "autoprefixer": "^10.4.2",
    "babel-loader": "^8.2.3",
    "eslint": "8.10.0",
    "eslint-config-next": "15.0.3",
    "postcss": "^8.4.8",
    "prettier": "^2.8.8",
    "tailwindcss": "^3.0.23",
    "typescript": "^5.3.2"
  },
  "packageManager": "yarn@3.2.3",
  "resolutions": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  },
  "overrides": {
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106"
  }
}
```

### Node.js version

v22.12.0

### Operating system name and version

Ubuntu 22.04.5

### Browser name

Brave, Safari

### What happended?

Followed the guide below, and that implementation does not work correctly. No order is created when  `place order` button is pressed, but the payment is successfully captured and multiple ``request to capture PaymentIntent`` are called.

https://docs.medusajs.com/resources/nextjs-starter/guides/customize-stripe

I solved this by adding the following to the .then statement in the file below
``src/modules/checkout/components/payment-button/index.tsx``

```ts
// added paymentIntent
.then(({ error, paymentIntent }) => {
        if (error) {
          const pi = error.payment_intent

          if (
            (pi && pi.status === "requires_capture") ||
            (pi && pi.status === "succeeded")
          ) {
            onPaymentCompleted()
          }

          setErrorMessage(error.message || null)
          return
        }
        // if payment intent is present and meets condition, process order
        if ((paymentIntent && paymentIntent.status === "requires_capture") || paymentIntent.status === "succeeded") {
          return onPaymentCompleted()
        }

        return
      })
  }
  ```

### Expected behavior

correct paymentElement implementation that successfully creates order after payment is captured and only one `request to capture a PaymentIntent` is called. 

``medusa-config.ts``
```ts
{
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/payment-stripe",
            id: "stripe",
            options: {
              apiKey: process.env.STRIPE_API_KEY,
              webhookSecret: process.env.STRIPE_WEBHOOK,
              automatic_payment_methods: true,
              capture: true,
            },
          },
        ],
      },
    },
    ```

### Actual behavior

With my posted fix above it does process the payment and create the order, however the payment capture is still called twice after the payment has already been captured. see full activity below

![image](https://github.com/user-attachments/assets/f12e3b92-b31a-46f0-8167-650d0f0ae4cd)
![image](https://github.com/user-attachments/assets/78ec8f74-8818-4a0a-b9d8-a5515001e43e)

Another weird part that is different from my previous implementation of paymentElement, is applepay payment confirmation is triggered when the `Continue to review` button is pressed. No payment is captured until the `Place order` button is pressed, but can be misleading from the customer experience.

![image](https://github.com/user-attachments/assets/68e7ed58-0e3e-4eb0-bb23-df67876ef0a1)

Additionally when using cashapp on desktop, it opens the authorize payment in a new window and if payment is authorized it successfully redirects to the order confirmation page, but the original checkout page throws the error below.

![image](https://github.com/user-attachments/assets/c67fcce2-337b-4be2-9257-a2be5785526e)

### Link to reproduction repo

https://dev.derftuned.com

**Comment by 420coupe** [comment]
I also have 2 orders that payment was captured but no orders were ever created, how would I manually create the orders/complete the carts for these two successful payments?

**Comment by sradevski** [comment]
I am doing some improvements to Stripe currently, and I will look into this as well in the next few days.

**Comment by sradevski** [comment]
No updates yet, we'll let you know once we've started working on it.

**Comment by sradevski** [comment]
Hey @420coupe I am adding idempotency keys here: https://github.com/medusajs/medusa/pull/11494 which I believe should resolve the issue with the double payment intents.

I am not sure what happened in the cases where the place order failed, we'll maybe need a bit more info as I was unable to reproduce it with a card payment.

**Comment by 420coupe** [comment]
> Hey @420coupe I am adding idempotency keys here: https://github.com/medusajs/medusa/pull/11494 which I believe should resolve the issue with the double payment intents.
> 
> I am not sure what happened in the cases where the place order failed, we'll maybe need a bit more info as I was unable to reproduce it with a card payment.

The failed orders only happens with two step payments ie cashapp/applepay/googlepay/amazonpay. It will successfully capture the payment on stripe side but fails to process the order on Medusa side with the above failure that order address already exists.

**Comment by 420coupe** [comment]
So i've updated to latest medusajs v2.6.0 and updated nextjs to current. The two step verification now correctly works on the original checkout page, but fails on the return url. I believe there is a race condition being faced between which processes placeOrder() first whether the original page receives response from stripe.confirmPayment first or if the pop up page with payment authorization hits server first and achieves the placeOrder() via return url and successfully redirects. 

```log

 ⨯ Error: Error setting up the request: Order address with id: caaddr_01JNKWRCQVRJBW3NHZAW70HR44, already exists.
    at medusaError (src/lib/util/medusa-error.ts:20:10)
    at async placeOrder (src/lib/data/cart.ts:390:18)
    at async GET (src/app/[countryCode]/(main)/order/capture-payment/[cartId]/route.ts:39:16)
  18 |   } else {
  19 |     // Something happened in setting up the request that triggered an Error
> 20 |     throw new Error("Error setting up the request: " + error.message)
     |          ^
  21 |   }
  22 | }
  23 |
 ⨯ Error: Error setting up the request: Order address with id: caaddr_01JNKWRCQVRJBW3NHZAW70HR44, already exists.
    at medusaError (src/lib/util/medusa-error.ts:20:10)
    at async placeOrder (src/lib/data/cart.ts:390:18)
    at async GET (src/app/[countryCode]/(main)/order/capture-payment/[cartId]/route.ts:39:16)
  18 |   } else {
  19 |     // Something happened in setting up the request that triggered an Error
> 20 |     throw new Error("Error setting up the request: " + error.message)
     |          ^
  21 |   }
  22 | }
  23 |
 GET /us/order/capture-payment/cart_01JNJ708W0K6XAV7A7VP65GRBK?country_code=us&payment_intent=pi_3QzNhZK6QjZA3FWk0Ic7v3MK&payment_intent_client_secret=pi_3QzNhZK6QjZA3FWk0Ic7v3MK_secret_AH5CNEKVBFPiNwwwzJMcacHil&redirect_status=succeeded 500 in 10447ms
```

**Comment by 420coupe** [comment]
so i solved this with my original implementation of the payment process page. I've tried porting the my working implementation to the version in the guide and still no luck. 

With my version below it works correctly and processes on both screens, I haven't been able to replicate the issue with this version.

order/payment/[cardId]/page.tsx
```tsx
"use client"
import { useEffect, useRef } from "react"
import { placeOrder } from "@lib/data/cart"
import { retrieveOrderByPaymentCollectionId } from "@lib/data/orders"
import { findPaymentCollectionIdByIntent } from "@lib/data/payment"
import { useRouter, useParams, useSearchParams } from "next/navigation"
import SkeletonOrderConfirmed from "@modules/skeletons/templates/skeleton-order-confirmed"
import medusaError from "@lib/util/medusa-error"

export default function OrderPaymentConfirmedPage() {
  const router = useRouter()
  const params = useParams()
  const searchParams = useSearchParams()
  const cartId = params.cartId as string
  const payment_intent = searchParams.get("payment_intent")
  const payment_intent_client_secret = searchParams.get(
    "payment_intent_client_secret"
  )
  const redirect_status = searchParams.get("redirect_status") || ""
  const countryCode = searchParams.get("country_code")
  const isPlacingOrder = useRef(false)

  useEffect(() => {
    const handlePaymentConfirmation = async () => {
      if (redirect_status === "failed") {
        router.push(`/checkout?step=payment`)
        return
      }
      if (redirect_status === "succeeded") {
        await new Promise((resolve) => setTimeout(resolve, 5000))
        try {
          if (payment_intent && payment_intent_client_secret) {
            const paymentCollectionId = await findPaymentCollectionIdByIntent(
              payment_intent,
              payment_intent_client_secret
            )

            if (paymentCollectionId) {
              const orderId = await retrieveOrderByPaymentCollectionId(
                paymentCollectionId
              )
              if (orderId) {
                router.push(`/order/${orderId}/confirmed`)
                return
              }
            }
          }

          if (cartId && !isPlacingOrder.current) {
            isPlacingOrder.current = true
            try {
              await placeOrder(cartId)
              return
            } catch (err) {
              medusaError(err)
            } finally {
              isPlacingOrder.current = false
            }
          }
          if (!cartId) {
            throw new Error("Cart ID not found.")
          }
        } catch (error) {
          medusaError(error)
        }
      }
    }
    handlePaymentConfirmation()
  }, [
    cartId,
    payment_intent,
    payment_intent_client_secret,
    redirect_status,
    router,
  ])

  return (
    <div>
      <SkeletonOrderConfirmed />
    </div>
  )
}
```


tried porting my logic over to guides version, this still caused failures on both, or one success one failure. 

order/capture-payment/[cardId]/route.ts
```ts
import { placeOrder, retrieveCart } from "@lib/data/cart"
import { retrieveOrderByPaymentCollectionId } from "@lib/data/orders"
import { findPaymentCollectionIdByIntent } from "@lib/data/payment"
import { NextRequest, NextResponse } from "next/server"

type Params = Promise<{ cartId: string }>

export async function GET(req: NextRequest, { params }: { params: Params }) {
  const { cartId } = await params
  const { searchParams } = req.nextUrl
  const origin = process.env.NEXT_PUBLIC_BASE_URL

  const paymentIntent = searchParams.get("payment_intent")
  const paymentIntentClientSecret = searchParams.get(
    "payment_intent_client_secret"
  )
  const redirectStatus = searchParams.get("redirect_status") || ""
  const countryCode = searchParams.get("country_code")

  try {
    const cart = await retrieveCart(cartId)
    if (!cart) {
      return NextResponse.redirect(`${origin}/${countryCode}`)
    }

    const paymentSession = cart.payment_collection?.payment_sessions?.find(
      (payment) => payment.data.id === paymentIntent
    )
    if (
      !paymentSession ||
      paymentSession.data.client_secret !== paymentIntentClientSecret ||
      !["pending", "succeeded"].includes(redirectStatus) ||
      !["pending", "authorized"].includes(paymentSession.status)
    ) {
      return NextResponse.redirect(
        `${origin}/${countryCode}/checkout?step=review&error=payment_failed`
      )
    }

    await new Promise((resolve) => setTimeout(resolve, 5000))

    if (paymentIntent && paymentIntentClientSecret) {
      const paymentCollectionId = await findPaymentCollectionIdByIntent(
        paymentIntent,
        paymentIntentClientSecret
      )
      if (paymentCollectionId) {
        const orderId = await retrieveOrderByPaymentCollectionId(
          paymentCollectionId
        )
        if (orderId) {
          return NextResponse.redirect(
            `${origin}/${countryCode}/order/${orderId}/confirmed`
          )
        }
      }
    }

    const order = await placeOrder(cartId)
    return NextResponse.redirect(
      `${origin}/${countryCode}/order/${order.id}/confirmed`
    )
  } catch (error) {
    console.error("Error in payment confirmation route:", error)
    return NextResponse.redirect(
      `${origin}/${countryCode}/checkout?step=review&error=payment_failed`
    )
  }
}
```

**Comment by theskollie** [comment]
Experiencing the same issue.
The paymentIntent solution above resolved the Card payment on the Stripe Payment element.
But the 2 Step payments (Cash App, Klarna etc) are still causing weird behaviors where the redirect opens a second tab which is redirected to the order success page but the initial checkout page that spawned the 2nd tab errors and is stuck on checkout.
@sradevski

**Comment by 420coupe** [comment]
Any update on this ever?

tested the guide again and original checkout window still stays spinning even with 1 step payment such as CC, receives the confirm response but button never updates nor moves with the recommended guide code.

**Comment by 420coupe** [comment]
> Hi @420coupe I think I have a similar problem. Did you manage to solve it? Everything seems to be working fine for me, but sometimes the payment reaches Stripe but doesn't show up in Medusa. I described it here:  [https://github.com/medusajs/medusa/issues/12790](https://github.com/medusajs/medusa/issues/12790).

Not really, my implementation still sometimes fails for 2 step payments such as cashapp. Where it tries to process the payment twice, one processes successfully and adds the order to the backend. The second fails because it was already processed, and then automatically issues a refund for the successful order above. 

This doesn't happen with every cashapp payment only on some. But I can't figure out how to replicate what users are doing to cause the issue.

**Comment by shahednasser** [comment]
Hey guys, thank you for creating this issue and sorry for the delay on our part. I've went through the guide and updated it to resolve previous issues and add more details around the implementation.

I should note that I haven't tested the implementation with every payment method in Stripe. So, if you still face any errors or issues, please consider opening a documentation issue on our main repo so that I can tackle it.
